<a href="https://colab.research.google.com/github/Thangamuniyandi894/mini_project_1/blob/main/global_seismic_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
!pip install pycountry
!pip install reverse_geocoder

Requirement already satisfied: pycountry in /usr/local/lib/python3.12/dist-packages (26.2.16)
Requirement already satisfied: reverse_geocoder in /usr/local/lib/python3.12/dist-packages (1.5.1)
Requirement already satisfied: numpy>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from reverse_geocoder) (2.0.2)
Requirement already satisfied: scipy>=0.17.1 in /usr/local/lib/python3.12/dist-packages (from reverse_geocoder) (1.16.3)

In [61]:
import requests
import pandas as pd
from datetime import datetime

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

all_records = []
start_year = datetime.now().year - 5   # last 5 years
end_year = datetime.now().year

for year in range(start_year, end_year + 1):
    for month in range(1, 13):
        start_date = f"{year}-{month:02d}-01"
        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

        response = requests.get(url, params=params)
        if response.status_code != 200:
            print(f"⚠️ Failed for {start_date}: {response.text[:200]}")
            continue

        try:
            data = response.json()
        except Exception as e:
            print(f"⚠️ JSON error for {start_date}: {e}")
            continue

        for f in data["features"]:
            p = f["properties"]
            g = f["geometry"]["coordinates"]
            all_records.append({
                "id": f.get("id"),
                "time": pd.to_datetime(p.get("time"), unit="ms"),
                "updated": pd.to_datetime(p.get("updated"), unit="ms"),
                "latitude": g[1] if g else None,
                "longitude": g[0] if g else None,
                "depth_km": g[2] if g else None,
                "mag": p.get("mag"),
                "magType": p.get("magType"),
                "place": p.get("place"),
                "status": p.get("status"),
                "tsunami": p.get("tsunami"),
                "alert": p.get("alert"),
                "felt": p.get("felt"),
                "cdi": p.get("cdi"),
                "mmi": p.get("mmi"),
                "sig": p.get("sig"),
                "net": p.get("net"),
                "code": p.get("code"),
                "ids": p.get("ids"),
                "sources": p.get("sources"),
                "types": p.get("types"),
                "nst": p.get("nst"),
                "dmin": p.get("dmin"),
                "rms": p.get("rms"),
                "gap": p.get("gap"),
                "type": p.get("type"),
                "magError": p.get("magError"),
                "depthError": p.get("depthError" ),
                "magNst": p.get("magNst"),
                "magSource": p.get("magSource")
            })







df = pd.DataFrame(all_records)

In [62]:
df['magError'].describe()

count       0
unique      0
top       NaN
freq      NaN
Name: magError, dtype: object

In [63]:
df['depthError'].describe()

count       0
unique      0
top       NaN
freq      NaN
Name: depthError, dtype: object

In [64]:
df['magNst'].describe()

count       0
unique      0
top       NaN
freq      NaN
Name: magNst, dtype: object

In [65]:
df['magSource'].describe()

count       0
unique      0
top       NaN
freq      NaN
Name: magSource, dtype: object

In [66]:
col_drop=['magError','depthError','magNst','magSource']

In [67]:
df.drop(columns=col_drop,inplace=True)

In [68]:
df

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,net,code,ids,sources,types,nst,dmin,rms,gap,type
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,us,6000ddi8,",us6000ddi8,",",us,",",dyfi,moment-tensor,origin,phase-data,",NaN,0.294,0.82,42.0,earthquake
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,reviewed,...,us,6000dev6,",us6000dev6,",",us,",",origin,phase-data,",NaN,1.471,0.29,64.0,earthquake
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",reviewed,...,us,6000dev5,",us6000dev5,",",us,",",origin,phase-data,",NaN,3.057,0.69,106.0,earthquake
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,mb,"114 km N of M?n?b, Iran",reviewed,...,us,6000ddhs,",us6000ddhs,",",us,",",origin,phase-data,",NaN,3.330,0.61,71.0,earthquake
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,us,6000dev4,",us6000dev4,",",us,",",origin,phase-data,",NaN,6.023,0.50,65.0,earthquake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117819,us6000thdk,2026-08-01 02:48:01.570,2026-08-02 14:50:42.040,41.3520,141.8958,82.29,5.5,mww,"57 km E of Mutsu, Japan",reviewed,...,us,6000thdk,",us6000thdk,usauto6000thdk,",",us,usauto,",",dyfi,internal-moment-tensor,losspager,moment-...",73.0,0.843,0.83,72.0,earthquake
117820,us6000tili,2026-08-01 02:42:39.840,2026-08-18 23:12:28.040,5.0135,125.2117,35.00,4.5,mb,"51 km SSW of Sarangani, Philippines",reviewed,...,us,6000tili,",us6000tili,",",us,",",origin,phase-data,",19.0,2.075,1.44,135.0,earthquake
117821,us6000thdg,2026-08-01 02:16:27.477,2026-08-21 05:21:16.194,9.7311,-83.8285,10.00,4.3,mb,"7 km SSE of Orosi, Costa Rica",reviewed,...,us,6000thdg,",us6000thdg,",",us,",",dyfi,origin,phase-data,",23.0,0.388,1.07,167.0,earthquake
117822,us6000thdc,2026-08-01 01:29:36.477,2026-08-21 05:18:40.040,35.4076,99.5171,10.00,4.5,mb,"195 km NW of Oula Xiuma, China",reviewed,...,us,6000thdc,",us6000thdc,",",us,",",origin,phase-data,",49.0,3.445,0.88,115.0,earthquake
117823,us6000thdb,2026-08-01 01:24:09.688,2026-08-21 05:15:30.040,18.9321,39.1938,10.00,4.7,mb,"164 km ENE of Tokār, Sudan",reviewed,...,us,6000thdb,",us6000thdb,",",us,",",origin,phase-data,",68.0,6.605,0.98,55.0,earthquake

# **UNDERSTANDING THE DATA**

In [69]:
df.shape

(117824, 26)

In [70]:
df.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,net,code,ids,sources,types,nst,dmin,rms,gap,type
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,us,6000ddi8,",us6000ddi8,",",us,",",dyfi,moment-tensor,origin,phase-data,",NaN,0.294,0.82,42.0,earthquake
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,reviewed,...,us,6000dev6,",us6000dev6,",",us,",",origin,phase-data,",NaN,1.471,0.29,64.0,earthquake
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",reviewed,...,us,6000dev5,",us6000dev5,",",us,",",origin,phase-data,",NaN,3.057,0.69,106.0,earthquake
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,mb,"114 km N of M?n?b, Iran",reviewed,...,us,6000ddhs,",us6000ddhs,",",us,",",origin,phase-data,",NaN,3.330,0.61,71.0,earthquake
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,us,6000dev4,",us6000dev4,",",us,",",origin,phase-data,",NaN,6.023,0.50,65.0,earthquake

In [71]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi',
       'sig', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms',
       'gap', 'type'],
      dtype='object')

In [72]:
df.dtypes

id                   object
time         datetime64[ns]
updated      datetime64[ns]
latitude            float64
longitude           float64
depth_km            float64
mag                 float64
magType              object
place                object
status               object
tsunami               int64
alert                object
felt                float64
cdi                 float64
mmi                 float64
sig                   int64
net                  object
code                 object
ids                  object
sources              object
types                object
nst                 float64
dmin                float64
rms                 float64
gap                 float64
type                 object
dtype: object

In [73]:
df.isnull().sum()

id                0
time              0
updated           0
latitude          0
longitude         0
depth_km          0
mag               0
magType           0
place             0
status            0
tsunami           0
alert        112997
felt          99834
cdi           99834
mmi          107493
sig               0
net               0
code              0
ids               0
sources           0
types             0
nst           27762
dmin           3977
rms              19
gap            3022
type              0
dtype: int64

In [74]:
df.duplicated().sum()

np.int64(0)

In [75]:
(df.isnull().sum() /len(df))*100

id            0.000000
time          0.000000
updated       0.000000
latitude      0.000000
longitude     0.000000
depth_km      0.000000
mag           0.000000
magType       0.000000
place         0.000000
status        0.000000
tsunami       0.000000
alert        95.903212
felt         84.731464
cdi          84.731464
mmi          91.231837
sig           0.000000
net           0.000000
code          0.000000
ids           0.000000
sources       0.000000
types         0.000000
nst          23.562262
dmin          3.375373
rms           0.016126
gap           2.564842
type          0.000000
dtype: float64

In [76]:
df.describe()

,time,updated,latitude,longitude,depth_km,mag,tsunami,felt,cdi,mmi,sig,nst,dmin,rms,gap
count,117824,117824,117824.000000,117824.000000,117824.000000,117824.000000,117824.000000,17990.000000,17990.000000,10331.000000,117824.000000,90062.000000,113847.000000,117805.000000,114802.000000
mean,2023-10-28 02:21:32.334899200,2024-02-13 09:19:58.872438016,12.222346,7.867633,71.585535,4.256001,0.005593,97.476098,3.219066,3.259992,287.499762,45.475206,3.189156,0.659231,122.741858
min,2021-01-01 00:14:07.580000,2021-01-01 10:15:32.601000,-84.493200,-179.999700,-3.740000,3.000000,0.000000,0.000000,0.000000,0.000000,138.000000,0.000000,0.000000,0.000000,8.000000
25%,2022-05-09 21:58:46.092249856,2022-09-03 21:03:18.040000,-14.194225,-111.922675,10.000000,4.000000,0.000000,1.000000,2.100000,2.336000,246.000000,20.000000,0.835000,0.490000,75.000000
50%,2023-11-06 01:56:51.063500032,2024-02-10 23:47:40.040000,14.879550,25.294750,21.460000,4.300000,0.000000,3.000000,3.100000,3.386000,284.000000,32.000000,1.815000,0.650000,113.000000
75%,2025-04-30 07:47:38.812000256,2025-09-02 21:23:38.040000,39.164825,130.565925,70.775500,4.600000,0.000000,10.000000,4.100000,4.122000,326.000000,56.000000,3.725500,0.820000,157.000000
max,2026-08-21 10:38:57.051000,2026-08-21 11:15:46.040000,87.375200,179.999400,683.578000,8.800000,1.000000,184672.000000,9.100000,9.953000,2910.000000,619.000000,62.558000,3.400000,359.000000
std,NaN,NaN,31.945277,129.032407,122.954968,0.611076,0.074578,1684.287920,1.500174,1.610416,92.025607,39.503139,4.457682,0.259235,62.916071

In [77]:
cat_col=df.select_dtypes(include="object").columns

In [78]:
for col in cat_col:
  print(f"____{col}_____")
  print(df[col].unique())
  print()

____id_____
['us6000ddi8' 'us6000dev6' 'us6000dev5' ... 'us6000thdg' 'us6000thdc'
 'us6000thdb']

____magType_____
['mwr' 'mb' 'md' 'mww' 'ml' 'mw' 'mwb' 'mb_lg' 'mwc' 'mlr' 'mlg' 'ms_20'
 'mlv' 'ml(texnet)' 'ms_vx' 'mwp' 'mh']

____place_____
['29 km SW of Villa Basilio Nievas, Argentina' 'Fiji region'
 '103 km SW of Basco, Philippines' ... '7 km SSE of Orosi, Costa Rica'
 '195 km NW of Oula Xiuma, China' '164 km ENE of Tokār, Sudan']

____status_____
['reviewed' 'automatic']

____alert_____
[None 'yellow' 'green' 'orange' 'red']

____net_____
['us' 'pr' 'hv' 'ak' 'ci' 'nn' 'nc' 'tx' 'iscgem' 'uu' 'ok' 'uw' 'nm' 'ew'
 'se' 'av' 'mb']

____code_____
['6000ddi8' '6000dev6' '6000dev5' ... '6000thdg' '6000thdc' '6000thdb']

____ids_____
[',us6000ddi8,' ',us6000dev6,' ',us6000dev5,' ... ',us6000thdg,'
 ',us6000thdc,' ',us6000thdb,']

____sources_____
[',us,' ',us,pr,' ',pr,' ',us,pt,iscgem,' ',pr,us,' ',ak,us,'
 ',us,iscgem,' ',iscgem,us,' ',us,ak,' ',us,hv,' ',hv,us,' ',ci,us,'
 ',us,nn,' ',nc,us,' ',us,usauto,iscgem,' ',ak,at,us,' ',usauto,us,'
 ',ak,us,at,' ',ak,iscgem,us,' ',us,pr,iscgem,' ',ak,us,iscgem,'
 ',usauto,iscgem,us,' ',usauto,us,iscgem,' ',usauto,pt,us,iscgem,'
 ',us,at,pt,usauto,iscgem,' ',usauto,pt,iscgem,us,'
 ',us,usauto,pt,at,iscgem,' ',mb,us,' ',pt,at,us,usauto,iscgem,' ',us,mb,'
 ',pt,us,pr,' ',at,pt,us,usauto,iscgem,' ',nn,us,' ',ew,at,nc,us,'
 ',nc,nn,us,' ',us,ak,ak,' ',pt,us,hv,' ',ak,ak,us,' ',ak,us,iscgem,ak,'
 ',pr,pt,us,' ',us,pt,at,iscgem,' ',ak,us,ak,' ',us,ak,ak,iscgem,'
 ',pt,us,iscgem,' ',us,tx,' ',iscgem,' ',us,at,pt,iscgem,' ',ak,'
 ',uu,us,' ',us,at,pt,ak,iscgem,' ',ak,at,us,iscgem,' ',us,uu,' ',us,nc,'
 ',us,usauto,at,iscgem,' ',tx,us,' ',us,ok,' ',us,at,usauto,ak,iscgem,'
 ',ew,nc,us,' ',us,usauto,pt,iscgem,' ',iscgem,ak,' ',ak,at,usauto,pt,us,'
 ',us,at,iscgem,' ',us,pt,' ',at,pt,us,iscgem,' ',us,ak,iscgem,'
 ',at,us,iscgem,' ',at,us,ak,iscgem,' ',pt,us,' ',pt,at,us,iscgem,'
 ',ci,nc,nn,us,' ',at,us,pt,iscgem,' ',ew,ci,us,' ',us,ak,at,' ',us,uw,'
 ',us,pr,pt,' ',ok,us,' ',pt,us,pr,iscgem,' ',usauto,at,pt,us,iscgem,'
 ',av,ak,us,' ',at,us,usauto,pt,iscgem,' ',us,usauto,at,pt,iscgem,'
 ',at,us,pt,usauto,iscgem,' ',pt,hv,us,' ',uw,us,' ',nn,us,ci,'
 ',usauto,iscgem,' ',us,pt,at,usauto,iscgem,' ',hv,'
 ',us,at,usauto,iscgem,' ',at,us,' ',hv,pt,us,' ',us,at,ak,iscgem,'
 ',at,usauto,us,ak,iscgem,' ',ak,at,usauto,pt,us,iscgem,' ',ci,at,us,ew,'
 ',ak,pt,us,' ',ak,iscgem,ak,at,us,usauto,pt,' ',usauto,at,iscgem,us,'
 ',nn,ew,nc,us,' ',us,ok,tx,' ',us,pt,usauto,at,iscgem,'
 ',usauto,at,us,iscgem,' ',us,us,' ',usauto,pt,at,us,iscgem,' ',nn,us,nc,'
 ',us,ci,' ',av,us,ak,' ',at,ak,us,' ',ew,nc,at,us,'
 ',us,usauto,ak,iscgem,' ',nm,us,' ',ci,' ',av,us,' ',ew,' ',ci,ci,ew,us,'
 ',uw,ew,uw,us,' ',ew,ci,usauto,pt,us,iscgem,' ',nn,nc,us,'
 ',at,ak,us,iscgem,' ',ak,usauto,pt,us,iscgem,' ',us,iscgem,ak,'
 ',ak,us,ak,at,pt,usauto,iscgem,' ',pt,us,at,pt,usauto,iscgem,'
 ',ew,nc,nn,us,' ',ew,nc,us,iscgem,' ',nc,ew,us,' ',nc,nc,nn,us,'
 ',nc,nn,us,ew,' ',nc,nn,nn,us,' ',nn,us,nc,iscgem,'
 ',ew,nc,ew,us,pt,nn,iscgem,' ',hv,us,hv,pt,' ',ci,us,ew,'
 ',nc,nn,us,nn,nn,' ',us,ak,at,pt,usauto,iscgem,' ',se,us,' ',us,se,'
 ',iscgemsup,us,' ',at,ak,iscgem,us,' ',at,iscgem,us,' ',us,nc,nn,'
 ',nc,us,nn,' ',us,at,usauto,pt,ak,iscgem,' ',usauto,us,ak,iscgem,'
 ',us,ci,ew,' ',ak,at,usauto,us,iscgem,' ',ak,usauto,us,iscgem,'
 ',at,us,usauto,ak,iscgem,' ',nc,ci,us,' ',ci,ew,us,'
 ',ak,us,at,pt,usauto,iscgem,' ',pt,us,hv,at,iscgem,'
 ',us,at,pt,at,usauto,iscgem,' ',iscgem,us,us,'
 ',at,us,pt,at,usauto,iscgem,' ',at,us,usauto,pt,ak,iscgem,' ',nc,us,ew,'
 ',us,ak,at,iscgem,' ',at,usauto,pt,us,ak,iscgem,' ',us,hv,pt,'
 ',at,ak,us,usauto,pt,iscgem,' ',ew,nc,us,at,usauto,pt,iscgem,'
 ',nc,us,iscgem,' ',us,av,ak,' ',pt,pr,us,' ',ak,av,us,' ',av,av,us,'
 ',at,us,usauto,iscgem,' ',us,usauto,' ',nn,ci,us,'
 ',us,usauto,at,ak,iscgem,' ',us,usauto,pt,' ',usauto,pt,us,'
 ',pt,us,at,usauto,' ',us,usauto,pt,at,' ',ew,nn,us,'
 ',at,us,usauto,pt,ak,' ',av,' ',us,av,av,ak,' ',at,us,usauto,pt,'
 ',pr,us,pr,' ',us,at,pt,' ',at,us,ak,' ',at,usauto,us,ak,'
 ',us,at,pt,usauto,ak,' ',at,ak,us,pt,usauto,' ',us,usauto,at,pt,'
 ',us,usauto,at,' ',ak,us,at,usauto,' ',ew,nc,pt,us,nn,' ',usauto,ak,us,'
 ',us,ak,at,ak,' ',ak,at,usauto,us,' ',at,us,pt,usauto,' ',usauto,at,us,'
 ',hv,us,pt,' ',ew,ci,at,us,' ',usauto,at,pt,us,' ',us,pt,at,usauto,'
 ',nc,us,ew,nn,' ',at,us,pt,' ',at,us,usauto,' ',at,us,ak,ak,'
 ',at,pt,us,usauto,' ',us,at,pt,usauto,' ',nc,us,uw,' ',nc,us,nn,ew,'
 ',pt,us,usauto,at,' ',nc,at,us,ew,' ',us,at,usauto,ak,' ',us,at,ak,'
 ',at,us,usauto,ak,' ',hv,us,hv,' ',pt,at,us,usauto,' ',hv,hv,us,'
 ',pt,us,usauto,' ',usauto,pt,at,us,' ',us,uw,nc,' ',us,at,se,at,'
 ',us,at,usauto,pt,ak,' ',us,usauto,ak,' ',at,nc,us,ew,' ',ak,us,av,'
 ',us,at,' ',tx,us,tx,' ',pt,us,at,usauto,at,' ',us,usauto,at,pt,hv,'
 ',us,at,usauto,ak,ak,' ',us,pt,at,' ',ew,nc,us,nn,' ',at,ak,us,usauto,'
 ',ak,at,us,av,' ',us,usauto,at,pt,ak,' ',us,at,ak,ak,'
 ',us,at,pt,at,usauto,' ',nc,us,ew,at,' ',tx,'
 ',at,us,pt,usauto,usauto,at,' ',ew,us,uw,' ',ak,at,us,ak,' ',ew,at,us,'
 ',us,tx,usauto,' ',at,pt,us,at,usauto,' ',ew,nc,us,at,usauto,pt,'
 ',at,us,nc,' ',ew,us,nc,' ',pt,usauto,us,usauto,' ',us,nc,ew,'
 ',ew,us,nc,at,usauto,' ',ak,us,at,usauto,pt,' ',uw,nn,us,'
 ',us,pt,usauto,' ',av,av,ak,us,' ',av,ak,av,us,' ',nc,' ',ew,at,us,nc,'
 ',us,nm,' ',us,ci,nc,nn,' ',ew,nc,at,usauto,us,' ',ew,us,ci,nc,nn,'
 ',ci,at,us,' ',ew,nc,usauto,pt,us,nn,' ',ew,nc,at,usauto,pt,us,nn,'
 ',at,pt,us,' ',us,at,usauto,av,ak,' ',av,ak,us,ak,' ',ew,nn,nc,us,'
 ',mb,' ',tx,tx,us,' ',ew,us,ci,' ',at,us,pt,usauto,ak,'
 ',us,at,at,pt,usauto,' ',ci,us,at,ew,' ',usauto,us,ak,' ',hv,pt,hv,us,'
 ',ew,nc,at,ew,us,' ',usauto,pt,us,ak,' ',at,ew,nc,us,'
 ',us,at,ak,usauto,ak,' ',us,at,usauto,pt,' ',at,us,tx,' ',ew,us,nc,nn,'
 ',nn,nc,uw,us,' ',pt,us,usauto,pt,ak,' ',ew,at,uw,us,' ',us,nc,uw,'
 ',pt,us,at,' ',pt,at,us,' ',at,us,pt,at,' ',us,uw,ew,'
 ',pt,us,pr,usauto,' ',ci,nc,us,' ',us,pt,pr,' ',ew,at,ci,us,'
 ',us,usauto,nc,' ',ew,us,mb,' ',ew,ci,us,at,' ',pt,us,hv,usauto,'
 ',at,usauto,pt,us,ak,' ',us,at,usauto,' ',at,us,pt,usauto,at,'
 ',at,us,pt,at,usauto,' ',nn,uw,us,' ',pt,us,pt,at,pt,usauto,'
 ',usauto,us,pt,' ',ew,us,ci,at,' ',us,at,usauto,pt,ak,ak,' ',us,hv,us,'
 ',ew,ci,usauto,us,' ',ew,us,nc,at,' ',at,us,pt,ak,'
 ',usauto,ew,us,at,pt,' ',ok,ok,us,' ',ew,us,ci,at,usauto,' ',uw,us,ew,'
 ',hv,pt,us,usauto,at,' ',uu,mb,us,' ',ci,ew,ci,at,us,'
 ',ew,at,us,usauto,pt,' ',ew,ci,us,nn,' ',ci,us,nn,' ',ci,nn,us,'
 ',ci,us,nn,ew,' ',ak,ak,us,ak,' ',ew,nc,us,nc,' ',ew,nc,nc,us,us,'
 ',nn,nn,us,' ',us,ew,nn,usauto,pt,nn,' ',ak,us,usauto,'
 ',us,ak,at,usauto,ak,' ',us,usauto,ak,ak,' ',ak,us,at,pt,usauto,'
 ',ew,us,nc,at,usauto,pt,' ',ak,ak,usauto,us,' ',usauto,at,pt,us,ak,'
 ',ci,ci,us,' ',uw,us,nn,' ',ew,ci,us,at,usauto,pt,'
 ',ak,at,usauto,us,av,' ',nc,at,us,' ',us,ak,av,' ',at,usauto,us,'
 ',at,usauto,us,pt,at,usauto,' ',pt,at,usauto,us,' ',us,nn,usauto,'
 ',usauto,pr,us,usauto,pt,' ',at,ak,us,ak,' ',us,mb,uu,'
 ',at,ak,us,usauto,pt,' ',at,ew,ci,us,' ',us,ak,usauto,' ',nn,ew,us,nc,'
 ',ew,ci,us,usauto,' ',at,us,pr,' ',usauto,us,pr,' ',pt,usauto,us,'
 ',uw,nc,us,' ',nn,us,ci,ew,' ',ew,us,nn,usauto,' ',us,usauto,at,ak,'
 ',ew,us,nc,usauto,' ',ak,usauto,at,' ',ew,nc,us,at,' ',ew,nn,us,usauto,'
 ',ak,usauto,us,at,' ',us,nc,usauto,at,ew,' ',av,ak,' ',usauto,us,at,'
 ',nn,uu,us,' ',nc,usauto,us,at,ew,' ',at,us,usauto,nc,ew,'
 ',usauto,at,us,ak,' ',uu,' ',us,ew,']

____types_____
[',dyfi,moment-tensor,origin,phase-data,' ',origin,phase-data,'
 ',dyfi,impact-text,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,origin,phase-data,' ',moment-tensor,origin,phase-data,'
 ',dyfi,losspager,origin,phase-data,shakemap,'
 ',dyfi,origin,phase-data,shakemap,' ',associate,origin,phase-data,'
 ',dyfi,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',losspager,origin,phase-data,shakemap,'
 ',dyfi,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,focal-mechanism,nearby-cities,origin,phase-data,scitech-link,'
 ',dyfi,impact-text,moment-tensor,origin,phase-data,'
 ',origin,phase-data,shakemap,'
 ',dyfi,losspager,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shakemap,'
 ',dyfi,internal-moment-tensor,origin,phase-data,'
 ',dyfi,impact-link,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',internal-moment-tensor,origin,phase-data,'
 ',dyfi,internal-moment-tensor,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,ground-failure,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,impact-text,origin,phase-data,shakemap,'
 ',internal-moment-tensor,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',internal-moment-tensor,losspager,origin,phase-data,shakemap,'
 ',internal-moment-tensor,internal-origin,origin,phase-data,'
 ',dyfi,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,nearby-cities,origin,phase-data,scitech-link,'
 ',dyfi,general-text,ground-failure,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,focal-mechanism,nearby-cities,origin,phase-data,scitech-link,shakemap,'
 ',dyfi,internal-moment-tensor,moment-tensor,origin,phase-data,'
 ',impact-text,origin,phase-data,' ',internal-origin,origin,phase-data,'
 ',dyfi,finite-fault,ground-failure,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',internal-moment-tensor,moment-tensor,origin,phase-data,'
 ',dyfi,focal-mechanism,impact-link,losspager,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',dyfi,focal-mechanism,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shakemap,'
 ',dyfi,focal-mechanism,losspager,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shakemap,'
 ',dyfi,impact-text,internal-moment-tensor,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,general-text,ground-failure,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,significance,'
 ',nearby-cities,origin,phase-data,scitech-link,shakemap,'
 ',dyfi,internal-origin,origin,phase-data,'
 ',dyfi,finite-fault,ground-failure,impact-text,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',losspager,moment-tensor,origin,phase-data,shakemap,'
 ',associate,impact-text,origin,phase-data,'
 ',internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,impact-text,origin,phase-data,'
 ',dyfi,ground-failure,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',origin,' ',nearby-cities,origin,phase-data,scitech-link,'
 ',dyfi,impact-link,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,nearby-cities,origin,phase-data,scitech-link,shakemap,'
 ',dyfi,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,impact-link,internal-moment-tensor,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,focal-mechanism,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',dyfi,ground-failure,impact-link,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',focal-mechanism,nearby-cities,origin,phase-data,scitech-link,'
 ',dyfi,impact-link,moment-tensor,origin,phase-data,'
 ',impact-link,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,impact-text,losspager,origin,phase-data,shakemap,'
 ',dyfi,ground-failure,impact-link,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,ground-failure,losspager,origin,phase-data,shakemap,'
 ',associate,dyfi,finite-fault,general-text,ground-failure,impact-link,impact-text,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,ground-failure,impact-link,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,focal-mechanism,losspager,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',dyfi,impact-link,losspager,origin,phase-data,shakemap,'
 ',earthquake-name,moment-tensor,origin,phase-data,'
 ',ground-failure,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,finite-fault,general-text,ground-failure,impact-link,impact-text,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',associate,dyfi,focal-mechanism,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',dyfi,focal-mechanism,moment-tensor,nearby-cities,origin,phase-data,scitech-link,'
 ',moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,ground-failure,impact-text,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,internal-origin,moment-tensor,origin,phase-data,'
 ',earthquake-name,origin,phase-data,'
 ',dyfi,focal-mechanism,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',dyfi,focal-mechanism,losspager,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',impact-link,moment-tensor,origin,phase-data,'
 ',impact-text,internal-moment-tensor,losspager,origin,phase-data,shakemap,'
 ',dyfi,impact-link,origin,phase-data,'
 ',associate,dyfi,finite-fault,general-text,ground-failure,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,ground-failure,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shakemap,'
 ',ground-failure,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',internal-moment-tensor,internal-origin,moment-tensor,origin,phase-data,'
 ',earthquake-name,internal-moment-tensor,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',internal-moment-tensor,internal-origin,losspager,origin,phase-data,shakemap,'
 ',internal-moment-tensor,origin,'
 ',dyfi,internal-moment-tensor,losspager,origin,phase-data,shakemap,'
 ',earthquake-name,losspager,origin,phase-data,shakemap,'
 ',associate,dyfi,earthquake-name,finite-fault,general-text,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,impact-text,internal-moment-tensor,losspager,origin,phase-data,shakemap,'
 ',dyfi,finite-fault,general-text,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,ground-failure,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',associate,dyfi,general-text,ground-failure,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,internal-moment-tensor,internal-origin,moment-tensor,origin,phase-data,'
 ',dyfi,impact-text,internal-moment-tensor,origin,phase-data,'
 ',dyfi,impact-link,internal-moment-tensor,moment-tensor,origin,phase-data,trump-origin,'
 ',dyfi,impact-link,internal-moment-tensor,losspager,moment-tensor,origin,phase-data,shakemap,trump-origin,'
 ',origin,phase-data,trump-origin,' ',impact-link,origin,phase-data,'
 ',dyfi,internal-origin,origin,phase-data,shakemap,'
 ',impact-link,internal-moment-tensor,moment-tensor,origin,phase-data,'
 ',earthquake-name,internal-moment-tensor,origin,phase-data,'
 ',dyfi,impact-text,internal-moment-tensor,moment-tensor,origin,phase-data,'
 ',dyfi,internal-origin,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,impact-link,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',associate,dyfi,focal-mechanism,losspager,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',associate,dyfi,impact-link,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,trump-origin,'
 ',internal-origin,moment-tensor,origin,phase-data,'
 ',associate,dyfi,ground-failure,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,trump-shakemap,'
 ',associate,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,finite-fault,general-text,ground-failure,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,general-text,ground-failure,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,earthquake-name,origin,phase-data,'
 ',dyfi,nearby-cities,origin,phase-data,'
 ',impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,impact-link,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,earthquake-name,ground-failure,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,focal-mechanism,impact-link,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',internal-origin,losspager,origin,phase-data,shakemap,'
 ',impact-link,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,origin,phase-data,trump-origin,'
 ',dyfi,ground-failure,internal-moment-tensor,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',associate,origin,shake-alert,'
 ',associate,disassociate,dyfi,nearby-cities,origin,phase-data,scitech-link,shakemap,trump-origin,'
 ',associate,dyfi,focal-mechanism,nearby-cities,origin,phase-data,scitech-link,shake-alert,'
 ',associate,dyfi,moment-tensor,origin,phase-data,shake-alert,shakemap,'
 ',dyfi,focal-mechanism,losspager,nearby-cities,origin,phase-data,scitech-link,shakemap,'
 ',associate,dyfi,focal-mechanism,ground-failure,internal-moment-tensor,internal-origin,losspager,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',dyfi,general-text,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,general-text,ground-failure,impact-link,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,focal-mechanism,origin,phase-data,scitech-link,'
 ',ground-failure,impact-link,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,focal-mechanism,origin,phase-data,scitech-link,shakemap,'
 ',associate,dyfi,earthquake-name,finite-fault,general-text,ground-failure,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,trump-losspager,trump-shakemap,'
 ',dyfi,ground-failure,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',associate,dyfi,ground-failure,impact-link,impact-text,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',dyfi,impact-text,losspager,moment-tensor,origin,phase-data,shakemap,'
 ',disassociate,dyfi,origin,phase-data,' ',losspager,origin,phase-data,'
 ',dyfi,focal-mechanism,ground-failure,losspager,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',dyfi,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',associate,dyfi,focal-mechanism,nearby-cities,origin,phase-data,scitech-link,shakemap,'
 ',dyfi,ground-failure,losspager,nearby-cities,origin,phase-data,shakemap,'
 ',associate,dyfi,earthquake-name,finite-fault,focal-mechanism,general-text,ground-failure,impact-text,internal-origin,losspager,moment-tensor,nearby-cities,origin,phase-data,scitech-link,shake-alert,shakemap,'
 ',associate,disassociate,dyfi,losspager,origin,phase-data,shakemap,'
 ',dyfi,losspager,moment-tensor,origin,phase-data,shakemap,trump-origin,'

In [79]:
for col in cat_col:
  print(f"____{col}_____")
  print(df[col].value_counts())
  print()

____id_____
id
pr71526913       1
us6000thex       1
aka2026pccmkv    1
us6000they       1
us6000thf3       1
                ..
us6000dev4       1
us6000ddhs       1
us6000dev5       1
us6000dev6       1
us6000ddi8       1
Name: count, Length: 117824, dtype: int64

____magType_____
magType
mb            83460
ml            16976
mww            7265
md             6448
mwr            2781
mw              670
mb_lg           126
ml(texnet)       43
mwb              32
mlr              10
mlv               5
mwc               2
ms_vx             2
ms_20             1
mlg               1
mwp               1
mh                1
Name: count, dtype: int64

____place_____
place
South Sandwich Islands region                   3181
south of the Fiji Islands                       2049
Kermadec Islands region                         1964
Fiji region                                     1332
southeast of the Loyalty Islands                1097
                                                ...
38 km SE of Jinka, Ethiopia                        1
125 km SW of Rabaul, Papua New Guinea              1
4 km NNE of Jayapura, Indonesia                    1
43 km W of Kandrian, Papua New Guinea              1
154 km SSW of Curahuara de Carangas, Bolivia       1
Name: count, Length: 64809, dtype: int64

____status_____
status
reviewed     117659
automatic       165
Name: count, dtype: int64

____alert_____
alert
green     4634
yellow     140
red         28
orange      25
Name: count, dtype: int64

____net_____
net
us        102978
pr          6430
ak          3794
tx          1019
nc           992
hv           930
ci           902
nn           456
uu           110
ok            92
uw            57
nm            22
se            18
iscgem        16
av             5
ew             2
mb             1
Name: count, dtype: int64

____code_____
code
71526913       1
6000thex       1
a2026pccmkv    1
6000they       1
6000thf3       1
              ..
6000dev4       1
6000ddhs       1
6000dev5       1
6000dev6       1
6000ddi8       1
Name: count, Length: 117824, dtype: int64

____ids_____
ids
,pr71526913,       1
,us6000thex,       1
,aka2026pccmkv,    1
,us6000they,       1
,us6000thf3,       1
                  ..
,us6000dev4,       1
,us6000ddhs,       1
,us6000dev5,       1
,us6000dev6,       1
,us6000ddi8,       1
Name: count, Length: 117824, dtype: int64

____sources_____
sources
,us,                       85751
,ak,us,                    10338
,us,ak,                     3046
,us,pr,                     2921
,pr,                        2754
                           ...
,ew,ci,us,usauto,              1
,ew,ci,us,at,usauto,pt,        1
,ak,at,usauto,us,av,           1
,nc,at,us,                     1
,us,ew,                        1
Name: count, Length: 374, dtype: int64

____types_____
types
,origin,phase-data,                                                                                                                          89595
,dyfi,origin,phase-data,                                                                                                                      8962
,origin,phase-data,shakemap,                                                                                                                  2459
,earthquake-name,origin,phase-data,                                                                                                           2172
,moment-tensor,origin,phase-data,                                                                                                             1397
                                                                                                                                             ...
,dyfi,earthquake-name,general-text,impact-link,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap,        1
,associate,general-header,impact-text,origin,phase-data,shakemap,                                                                                1
,associate,dyfi,internal-moment-tensor,moment-tensor,origin,phase-data,                                                                          1
,dyfi,general-text,moment-tensor,origin,phase-data,significance,                                                                                 1
,dyfi,event-sequence,losspager,moment-tensor,oaf,origin,phase-data,shakemap,trump-shakemap,                                                      1
Name: count, Length: 576, dtype: int64

____type_____
type
earthquake                116929
mining explosion             850
ice quake                     13
volcanic eruption             12
experimental explosion         5
other event                    5
mine collapse                  3
landslide                      3
quarry blast                   2
Landslide                      1
explosion                      1
Name: count, dtype: int64

In [80]:
col_drop2=['code','updated','ids','sources']

In [81]:
df.drop(columns=col_drop2,inplace=True)

**NULL VALUES HANDLING**

In [82]:
df[['felt','cdi','mmi']]=df[['felt','cdi','mmi']].fillna(0)

In [83]:
cols=['nst','dmin','rms','gap']

In [84]:
for col in cols:
  df[col]=df[col].fillna(df[col].median())

In [85]:
def get_alert(mag):
  if mag <5.5:
    return 'green'
  elif 5.5<=mag<6.5:
    return 'yellow'
  elif 6.5<=mag<7.5:
    return 'orange'
  else:
    return 'red'

In [86]:
df['alert']=df['alert'].fillna(df['mag'].apply(get_alert))

In [87]:
df['year']=df['time'].dt.year
df['month']=df['time'].dt.month_name()
df['day']=df['time'].dt.day
df['day_of_week']=df['time'].dt.day_name()
df['hour']=df['time'].dt.hour

In [88]:
df

,id,time,latitude,longitude,depth_km,mag,magType,place,status,tsunami,...,nst,dmin,rms,gap,type,year,month,day,day_of_week,hour
0,us6000ddi8,2021-01-31 23:20:49.923,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,0,...,32.0,0.294,0.82,42.0,earthquake,2021,January,31,Sunday,23
1,us6000dev6,2021-01-31 23:08:17.161,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,reviewed,0,...,32.0,1.471,0.29,64.0,earthquake,2021,January,31,Sunday,23
2,us6000dev5,2021-01-31 22:54:19.760,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",reviewed,0,...,32.0,3.057,0.69,106.0,earthquake,2021,January,31,Sunday,22
3,us6000ddhs,2021-01-31 22:06:00.832,28.1524,57.2570,10.00,4.9,mb,"114 km N of M?n?b, Iran",reviewed,0,...,32.0,3.330,0.61,71.0,earthquake,2021,January,31,Sunday,22
4,us6000dev4,2021-01-31 21:51:14.016,71.3212,-3.7578,10.00,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,0,...,32.0,6.023,0.50,65.0,earthquake,2021,January,31,Sunday,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117819,us6000thdk,2026-08-01 02:48:01.570,41.3520,141.8958,82.29,5.5,mww,"57 km E of Mutsu, Japan",reviewed,0,...,73.0,0.843,0.83,72.0,earthquake,2026,August,1,Saturday,2
117820,us6000tili,2026-08-01 02:42:39.840,5.0135,125.2117,35.00,4.5,mb,"51 km SSW of Sarangani, Philippines",reviewed,0,...,19.0,2.075,1.44,135.0,earthquake,2026,August,1,Saturday,2
117821,us6000thdg,2026-08-01 02:16:27.477,9.7311,-83.8285,10.00,4.3,mb,"7 km SSE of Orosi, Costa Rica",reviewed,0,...,23.0,0.388,1.07,167.0,earthquake,2026,August,1,Saturday,2
117822,us6000thdc,2026-08-01 01:29:36.477,35.4076,99.5171,10.00,4.5,mb,"195 km NW of Oula Xiuma, China",reviewed,0,...,49.0,3.445,0.88,115.0,earthquake,2026,August,1,Saturday,1
117823,us6000thdb,2026-08-01 01:24:09.688,18.9321,39.1938,10.00,4.7,mb,"164 km ENE of Tokār, Sudan",reviewed,0,...,68.0,6.605,0.98,55.0,earthquake,2026,August,1,Saturday,1

In [89]:
def get_depth_catagory(depth):
  if depth <=70:
    return 'shallow'
  elif depth <=300:
    return 'intermediate'
  else:
    return 'deep'

In [90]:

df['depth_catagory']=df['depth_km'].apply(get_depth_catagory)

In [91]:
def mag_flag(mag):
  if mag>=7.0:
    return 'Destructive'
  elif mag>=6.0:
    return 'Storng'
  else:
    return 'Normal'

In [92]:
df['mag_type_flag']=df['mag'].apply(mag_flag)

In [93]:
cat_col=df.select_dtypes(include="object").columns

In [94]:
for col in cat_col:
  df[col]=df[col].astype(str).str.lower().str.strip()

In [104]:
import reverse_geocoder as rg
coords = list(zip(df['latitude'], df['longitude']))
results = rg.search(coords)
df['country_code'] = [res['cc'] for res in results]

In [105]:
df

,id,time,latitude,longitude,depth_km,mag,magType,place,status,tsunami,...,gap,type,year,month,day,day_of_week,hour,depth_catagory,mag_type_flag,country_code
0,us6000ddi8,2021-01-31 23:20:49.923,-31.7493,-68.9337,17.27,4.7,mwr,"29 km sw of villa basilio nievas, argentina",reviewed,0,...,42.0,earthquake,2021,january,31,sunday,23,shallow,normal,AR
1,us6000dev6,2021-01-31 23:08:17.161,-15.4902,-177.2052,426.71,4.1,mb,fiji region,reviewed,0,...,64.0,earthquake,2021,january,31,sunday,23,deep,normal,WF
2,us6000dev5,2021-01-31 22:54:19.760,19.7529,121.3159,46.73,4.7,mb,"103 km sw of basco, philippines",reviewed,0,...,106.0,earthquake,2021,january,31,sunday,22,shallow,normal,PH
3,us6000ddhs,2021-01-31 22:06:00.832,28.1524,57.2570,10.00,4.9,mb,"114 km n of m?n?b, iran",reviewed,0,...,71.0,earthquake,2021,january,31,sunday,22,shallow,normal,IR
4,us6000dev4,2021-01-31 21:51:14.016,71.3212,-3.7578,10.00,4.0,mb,"184 km ene of olonkinbyen, svalbard and jan mayen",reviewed,0,...,65.0,earthquake,2021,january,31,sunday,21,shallow,normal,SJ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117819,us6000thdk,2026-08-01 02:48:01.570,41.3520,141.8958,82.29,5.5,mww,"57 km e of mutsu, japan",reviewed,0,...,72.0,earthquake,2026,august,1,saturday,2,intermediate,normal,JP
117820,us6000tili,2026-08-01 02:42:39.840,5.0135,125.2117,35.00,4.5,mb,"51 km ssw of sarangani, philippines",reviewed,0,...,135.0,earthquake,2026,august,1,saturday,2,shallow,normal,PH
117821,us6000thdg,2026-08-01 02:16:27.477,9.7311,-83.8285,10.00,4.3,mb,"7 km sse of orosi, costa rica",reviewed,0,...,167.0,earthquake,2026,august,1,saturday,2,shallow,normal,CR
117822,us6000thdc,2026-08-01 01:29:36.477,35.4076,99.5171,10.00,4.5,mb,"195 km nw of oula xiuma, china",reviewed,0,...,115.0,earthquake,2026,august,1,saturday,1,shallow,normal,CN
117823,us6000thdb,2026-08-01 01:24:09.688,18.9321,39.1938,10.00,4.7,mb,"164 km ene of tokār, sudan",reviewed,0,...,55.0,earthquake,2026,august,1,saturday,1,shallow,normal,SD

In [106]:
import pycountry

In [100]:
def get_country_name(code):
    try:
        return pycountry.countries.get(alpha_2=code.upper()).name.lower()
    except:
        return 'unknown'

In [108]:
df['country'] = df['country_code'].apply(get_country_name)

In [109]:
df

,id,time,latitude,longitude,depth_km,mag,magType,place,status,tsunami,...,type,year,month,day,day_of_week,hour,depth_catagory,mag_type_flag,country_code,country
0,us6000ddi8,2021-01-31 23:20:49.923,-31.7493,-68.9337,17.27,4.7,mwr,"29 km sw of villa basilio nievas, argentina",reviewed,0,...,earthquake,2021,january,31,sunday,23,shallow,normal,AR,argentina
1,us6000dev6,2021-01-31 23:08:17.161,-15.4902,-177.2052,426.71,4.1,mb,fiji region,reviewed,0,...,earthquake,2021,january,31,sunday,23,deep,normal,WF,wallis and futuna
2,us6000dev5,2021-01-31 22:54:19.760,19.7529,121.3159,46.73,4.7,mb,"103 km sw of basco, philippines",reviewed,0,...,earthquake,2021,january,31,sunday,22,shallow,normal,PH,philippines
3,us6000ddhs,2021-01-31 22:06:00.832,28.1524,57.2570,10.00,4.9,mb,"114 km n of m?n?b, iran",reviewed,0,...,earthquake,2021,january,31,sunday,22,shallow,normal,IR,"iran, islamic republic of"
4,us6000dev4,2021-01-31 21:51:14.016,71.3212,-3.7578,10.00,4.0,mb,"184 km ene of olonkinbyen, svalbard and jan mayen",reviewed,0,...,earthquake,2021,january,31,sunday,21,shallow,normal,SJ,svalbard and jan mayen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117819,us6000thdk,2026-08-01 02:48:01.570,41.3520,141.8958,82.29,5.5,mww,"57 km e of mutsu, japan",reviewed,0,...,earthquake,2026,august,1,saturday,2,intermediate,normal,JP,japan
117820,us6000tili,2026-08-01 02:42:39.840,5.0135,125.2117,35.00,4.5,mb,"51 km ssw of sarangani, philippines",reviewed,0,...,earthquake,2026,august,1,saturday,2,shallow,normal,PH,philippines
117821,us6000thdg,2026-08-01 02:16:27.477,9.7311,-83.8285,10.00,4.3,mb,"7 km sse of orosi, costa rica",reviewed,0,...,earthquake,2026,august,1,saturday,2,shallow,normal,CR,costa rica
117822,us6000thdc,2026-08-01 01:29:36.477,35.4076,99.5171,10.00,4.5,mb,"195 km nw of oula xiuma, china",reviewed,0,...,earthquake,2026,august,1,saturday,1,shallow,normal,CN,china
117823,us6000thdb,2026-08-01 01:24:09.688,18.9321,39.1938,10.00,4.7,mb,"164 km ene of tokār, sudan",reviewed,0,...,earthquake,2026,august,1,saturday,1,shallow,normal,SD,sudan

In [110]:
df.drop(columns='country_code',inplace=True)

In [111]:
df['types']=df['types'].str.strip(',')

In [112]:
df

,id,time,latitude,longitude,depth_km,mag,magType,place,status,tsunami,...,gap,type,year,month,day,day_of_week,hour,depth_catagory,mag_type_flag,country
0,us6000ddi8,2021-01-31 23:20:49.923,-31.7493,-68.9337,17.27,4.7,mwr,"29 km sw of villa basilio nievas, argentina",reviewed,0,...,42.0,earthquake,2021,january,31,sunday,23,shallow,normal,argentina
1,us6000dev6,2021-01-31 23:08:17.161,-15.4902,-177.2052,426.71,4.1,mb,fiji region,reviewed,0,...,64.0,earthquake,2021,january,31,sunday,23,deep,normal,wallis and futuna
2,us6000dev5,2021-01-31 22:54:19.760,19.7529,121.3159,46.73,4.7,mb,"103 km sw of basco, philippines",reviewed,0,...,106.0,earthquake,2021,january,31,sunday,22,shallow,normal,philippines
3,us6000ddhs,2021-01-31 22:06:00.832,28.1524,57.2570,10.00,4.9,mb,"114 km n of m?n?b, iran",reviewed,0,...,71.0,earthquake,2021,january,31,sunday,22,shallow,normal,"iran, islamic republic of"
4,us6000dev4,2021-01-31 21:51:14.016,71.3212,-3.7578,10.00,4.0,mb,"184 km ene of olonkinbyen, svalbard and jan mayen",reviewed,0,...,65.0,earthquake,2021,january,31,sunday,21,shallow,normal,svalbard and jan mayen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117819,us6000thdk,2026-08-01 02:48:01.570,41.3520,141.8958,82.29,5.5,mww,"57 km e of mutsu, japan",reviewed,0,...,72.0,earthquake,2026,august,1,saturday,2,intermediate,normal,japan
117820,us6000tili,2026-08-01 02:42:39.840,5.0135,125.2117,35.00,4.5,mb,"51 km ssw of sarangani, philippines",reviewed,0,...,135.0,earthquake,2026,august,1,saturday,2,shallow,normal,philippines
117821,us6000thdg,2026-08-01 02:16:27.477,9.7311,-83.8285,10.00,4.3,mb,"7 km sse of orosi, costa rica",reviewed,0,...,167.0,earthquake,2026,august,1,saturday,2,shallow,normal,costa rica
117822,us6000thdc,2026-08-01 01:29:36.477,35.4076,99.5171,10.00,4.5,mb,"195 km nw of oula xiuma, china",reviewed,0,...,115.0,earthquake,2026,august,1,saturday,1,shallow,normal,china
117823,us6000thdb,2026-08-01 01:24:09.688,18.9321,39.1938,10.00,4.7,mb,"164 km ene of tokār, sudan",reviewed,0,...,55.0,earthquake,2026,august,1,saturday,1,shallow,normal,sudan

In [113]:
cat_col1=df.select_dtypes(include="object").columns

In [114]:
for col in cat_col1 :
  print(f"____{col}_____")
  print(df[col].value_counts())
  print()

____id_____
id
pr71526913       1
us6000thex       1
aka2026pccmkv    1
us6000they       1
us6000thf3       1
                ..
us6000dev4       1
us6000ddhs       1
us6000dev5       1
us6000dev6       1
us6000ddi8       1
Name: count, Length: 117824, dtype: int64

____magType_____
magType
mb            83460
ml            16976
mww            7265
md             6448
mwr            2781
mw              670
mb_lg           126
ml(texnet)       43
mwb              32
mlr              10
mlv               5
mwc               2
ms_vx             2
ms_20             1
mlg               1
mwp               1
mh                1
Name: count, dtype: int64

____place_____
place
south sandwich islands region       3181
south of the fiji islands           2049
kermadec islands region             1964
fiji region                         1332
southeast of the loyalty islands    1097
                                    ...
17 km ese of shemokmedi, georgia       1
9 km s of bni bouayach, morocco        1
27 km se of unalaska, alaska           1
51 km wsw of kulachi, pakistan         1
18 km s of yacuiba, bolivia            1
Name: count, Length: 64798, dtype: int64

____status_____
status
reviewed     117659
automatic       165
Name: count, dtype: int64

____alert_____
alert
green     117608
yellow       162
red           28
orange        26
Name: count, dtype: int64

____net_____
net
us        102978
pr          6430
ak          3794
tx          1019
nc           992
hv           930
ci           902
nn           456
uu           110
ok            92
uw            57
nm            22
se            18
iscgem        16
av             5
ew             2
mb             1
Name: count, dtype: int64

____types_____
types
origin,phase-data                                                                                                                          89595
dyfi,origin,phase-data                                                                                                                      8962
origin,phase-data,shakemap                                                                                                                  2459
earthquake-name,origin,phase-data                                                                                                           2172
moment-tensor,origin,phase-data                                                                                                             1397
                                                                                                                                           ...
dyfi,earthquake-name,general-text,impact-link,internal-moment-tensor,internal-origin,losspager,moment-tensor,origin,phase-data,shakemap        1
associate,general-header,impact-text,origin,phase-data,shakemap                                                                                1
associate,dyfi,internal-moment-tensor,moment-tensor,origin,phase-data                                                                          1
dyfi,general-text,moment-tensor,origin,phase-data,significance                                                                                 1
dyfi,event-sequence,losspager,moment-tensor,oaf,origin,phase-data,shakemap,trump-shakemap                                                      1
Name: count, Length: 576, dtype: int64

____type_____
type
earthquake                116929
mining explosion             850
ice quake                     13
volcanic eruption             12
other event                    5
experimental explosion         5
landslide                      4
mine collapse                  3
quarry blast                   2
explosion                      1
Name: count, dtype: int64

____month_____
month
july         11724
march        10931
august       10785
january      10579
april        10331
february     10065
may           9763
december      9675
june          9556
september     8316
october       8145
november      7954
Name: count, dtype: int64

____day_of_week_____
day_of_week
friday       17034
tuesday      17005
sunday       16902
monday       16835
wednesday    16825
saturday     16715
thursday     16508
Name: count, dtype: int64

____depth_catagory_____
depth_catagory
shallow         88157
intermediate    22779
deep             6888
Name: count, dtype: int64

____mag_type_flag_____
mag_type_flag
normal         117057
storng            681
destructive        86
Name: count, dtype: int64

____country_____
country
united states           18682
indonesia               10293
tonga                    8986
russian federation       8423
japan                    7524
                        ...
montserrat                  1
netherlands                 1
united arab emirates        1
cook islands                1
denmark                     1
Name: count, Length: 193, dtype: int64

In [115]:
df.isnull().sum()

id                0
time              0
latitude          0
longitude         0
depth_km          0
mag               0
magType           0
place             0
status            0
tsunami           0
alert             0
felt              0
cdi               0
mmi               0
sig               0
net               0
types             0
nst               0
dmin              0
rms               0
gap               0
type              0
year              0
month             0
day               0
day_of_week       0
hour              0
depth_catagory    0
mag_type_flag     0
country           0
dtype: int64

In [117]:
df['country'].value_counts()

country
united states           18682
indonesia               10293
tonga                    8986
russian federation       8423
japan                    7524
                        ...
montserrat                  1
netherlands                 1
united arab emirates        1
cook islands                1
denmark                     1
Name: count, Length: 193, dtype: int64

In [118]:
df

,id,time,latitude,longitude,depth_km,mag,magType,place,status,tsunami,...,gap,type,year,month,day,day_of_week,hour,depth_catagory,mag_type_flag,country
0,us6000ddi8,2021-01-31 23:20:49.923,-31.7493,-68.9337,17.27,4.7,mwr,"29 km sw of villa basilio nievas, argentina",reviewed,0,...,42.0,earthquake,2021,january,31,sunday,23,shallow,normal,argentina
1,us6000dev6,2021-01-31 23:08:17.161,-15.4902,-177.2052,426.71,4.1,mb,fiji region,reviewed,0,...,64.0,earthquake,2021,january,31,sunday,23,deep,normal,wallis and futuna
2,us6000dev5,2021-01-31 22:54:19.760,19.7529,121.3159,46.73,4.7,mb,"103 km sw of basco, philippines",reviewed,0,...,106.0,earthquake,2021,january,31,sunday,22,shallow,normal,philippines
3,us6000ddhs,2021-01-31 22:06:00.832,28.1524,57.2570,10.00,4.9,mb,"114 km n of m?n?b, iran",reviewed,0,...,71.0,earthquake,2021,january,31,sunday,22,shallow,normal,"iran, islamic republic of"
4,us6000dev4,2021-01-31 21:51:14.016,71.3212,-3.7578,10.00,4.0,mb,"184 km ene of olonkinbyen, svalbard and jan mayen",reviewed,0,...,65.0,earthquake,2021,january,31,sunday,21,shallow,normal,svalbard and jan mayen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117819,us6000thdk,2026-08-01 02:48:01.570,41.3520,141.8958,82.29,5.5,mww,"57 km e of mutsu, japan",reviewed,0,...,72.0,earthquake,2026,august,1,saturday,2,intermediate,normal,japan
117820,us6000tili,2026-08-01 02:42:39.840,5.0135,125.2117,35.00,4.5,mb,"51 km ssw of sarangani, philippines",reviewed,0,...,135.0,earthquake,2026,august,1,saturday,2,shallow,normal,philippines
117821,us6000thdg,2026-08-01 02:16:27.477,9.7311,-83.8285,10.00,4.3,mb,"7 km sse of orosi, costa rica",reviewed,0,...,167.0,earthquake,2026,august,1,saturday,2,shallow,normal,costa rica
117822,us6000thdc,2026-08-01 01:29:36.477,35.4076,99.5171,10.00,4.5,mb,"195 km nw of oula xiuma, china",reviewed,0,...,115.0,earthquake,2026,august,1,saturday,1,shallow,normal,china
117823,us6000thdb,2026-08-01 01:24:09.688,18.9321,39.1938,10.00,4.7,mb,"164 km ene of tokār, sudan",reviewed,0,...,55.0,earthquake,2026,august,1,saturday,1,shallow,normal,sudan

In [119]:
df.columns

Index(['id', 'time', 'latitude', 'longitude', 'depth_km', 'mag', 'magType',
       'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi', 'sig',
       'net', 'types', 'nst', 'dmin', 'rms', 'gap', 'type', 'year', 'month',
       'day', 'day_of_week', 'hour', 'depth_catagory', 'mag_type_flag',
       'country'],
      dtype='object')

In [120]:
df.to_csv('global_seismic_trends_miniproject1.csv',index=False)